README.md

Created ReadMe.md for Slip-Snapper repo.

:memo: (Repo) : Added ReadMe.md

---

README.md

Fixed URL badge links and added description for (1) contributor.

:memo: (repo) : Updated ReadMe.md

---

.github/workflow/MetaTest.yml

Created MetaTest.yml to promote a standard on PRs for labels and milestones.

:white_check_mark: (cicd): Created Meta tag workflow

---

.github/workflows/CItest.yml
.github/workflows/index.yml

🐛 (cicd): Removed e2e

---

frontend/apps/slip-snapper/package.json
frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx

Added a View Reports page that will allow users to view reports that have been previously generated.

✨ (feature/side-menu): Added ViewReports page

---

.github/workflows/BackendCITest.yml
.github/workflows/index.yml
frontend/apps/slip-snapper/src/app/App.tsx

Fixed index.yml navigation to find BackendCITest.yml

🐛 (cicd): fixed index.yml directory for backend

---

frontend/apps/slip-snapper/src/app/App.tsx
frontend/apps/slip-snapper/src/app/components/Menu.tsx
frontend/apps/slip-snapper/src/app/components/NavButtons.tsx
frontend/apps/slip-snapper/src/app/pages/Home.tsx
frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx

Added the Menu component which allows for navigation through the system using a burger menu interface.

✨ (ui): Added menu

---

frontend/apps/slip-snapper/src/app/pages/Home.tsx

Added "Expenditure Total" cards to home page.

💄 (ui): Added mock components

---

backend/api/src/index.ts
backend/api/src/users.json

Added the add, delete and update user calls to the api
addUser: adds a user to the "database"
post : http://localhost:1234/addUser
{ "name": "jeff", "age": "25" }
updateUser: updates a user in the "database"
post : http://localhost:1234/updateUser
{ "userId":"user1", "name": "jeff", "age": "25" }
deleteUser: adds a user to the "database"
post : http://localhost:1234/deleteItem
{ "userId":"user1" }

🎨 (feature-api): added the user api calls

---

.github/workflows/MetaTest.yml
frontend/apps/slip-snapper/src/app/components/TakePictureButton.tsx
frontend/apps/slip-snapper/src/app/pages/Home.tsx
frontend/apps/slip-snapper/src/hooks/usePhotoGallery.ts

Added functionality of taking or uploading a photo

✨ (feature): Added TakePicture functionality

---

frontend/apps/slip-snapper/src/app/App.tsx
frontend/apps/slip-snapper/src/app/components/Menu.tsx
frontend/apps/slip-snapper/src/app/components/NavButtons.tsx
frontend/apps/slip-snapper/src/app/pages/EditItem.tsx
frontend/apps/slip-snapper/src/app/testData.json

Added "Edit Item" page which will be used to demo the functionality of editing an item in the database.

✨ (ui): Added EditItem page

---

frontend/apps/slip-snapper/src/hooks/usePhotoGallery.ts
frontend/apps/slip-snapper/src/main.tsx
frontend/package.json
frontend/yarn.lock

Fixed Camera not prompting for taking a photo 
added pwa elements

:bug: (feature): Fixed take picture option

---

backend/api/package.json
backend/api/src/index.js
backend/api/src/items.json

Updated the add and update item call to reflect the new "database" structure should now be better to use in the frontend

🎨 (feature-api): updated the add and update item call

---

.github/workflows/BackendCITest.yml
.github/workflows/index.yml

added yarn test to run Jest tests on Node server.

:white_check_mark: (cicd): Added yarn test for Backend workflow

---

backend/api/apps/src/index.js

Updated the add item to account for additional field
Changed the file write structure so that the correct error will be displayed if an issue occurs

🎨 (feature-api): Updated api to account for change in "database"

---

.github/workflows/FrontendCItest.yml
.github/workflows/full.yml
README.md
frontend/apps/slip-snapper/src/app/pages/EditItem.tsx
frontend/apps/slip-snapper/src/app/pages/Home.tsx
frontend/apps/slip-snapper/src/app/pages/Profile.tsx
frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
frontend/jest.preset.js

Added codecov to get testing coverage of frontend.

✅ (cicd): Added codcov

---

frontend/apps/slip-snapper/src/app/App.spec.tsx
frontend/apps/slip-snapper/src/app/__snapshots__/App.spec.tsx.snap
frontend/package.json
frontend/yarn.lock

Added some Jest tests for snapshot and and descriptions.

:white_check_mark: (feature): Added some Jest Tests

---

frontend/apps/slip-snapper/src/app/App.tsx
frontend/apps/slip-snapper/src/app/pages/Home.tsx
frontend/apps/slip-snapper/src/app/pages/Register.tsx
frontend/apps/slip-snapper/src/app/theme/variables.css

Created a Register page for the app

✨ (ui) Added register page

---

backend/api/apps/src/index.js
backend/api/apps/tests/index.test.js

Added the unit test for the item api calls

✅ (feature-api): added unit test for all the item api calls

---

frontend/apps/slip-snapper/src/app/pages/Login.tsx

Added the username attribute for the login page

💄 (ui): added username component

---

frontend/apps/slip-snapper/src/app/pages/Login.tsx

Added Password component to the login page

💄 (ui): Added password component

---

frontend/apps/slip-snapper/src/app/pages/Register.css
frontend/apps/slip-snapper/src/app/pages/Register.tsx

Added css styling for the register page

💄 (ui): Added CSS for the register page

---

.github/workflows/index.yml
backend/api/apps/src/index.js
backend/api/package.json
frontend/apps/slip-snapper/src/app/components/FetchData.js

Made a function to call the api for editting an item in the database
Reintroduced the backend tests
Altered the pacakage.json for backend to point to correct location of tests

🎨 (ui-api): Connected the edit item ui to the api call

---

backend/api/apps/src/items.json
frontend/apps/slip-snapper/src/app/pages/Home.tsx

Added function for "Generate Report" buttons.

💄 (ui): Functions for "Generate Report" buttons

---

backend/api/README.md
frontend/README.md

Added ReadMe commands inside frontend and backend

:pencil: (documentation): Added some commands in Readme

---

frontend/apps/slip-snapper/src/app/pages/Login.tsx
frontend/apps/slip-snapper/src/app/pages/LoginRegister.css
frontend/apps/slip-snapper/src/app/pages/Register.tsx

Added styling for the login and register pages to use

💄 (ui): Styling for Login and Register

---

README.md

Added Demo 1 Recording link to README.md.

📝(repo): Added Demo 1 Recording to README.md

---

frontend/apps/slip-snapper/src/hooks/OCR.tsx
frontend/apps/slip-snapper/src/hooks/usePhotoGallery.ts
frontend/package.json
frontend/yarn.lock

Created function to create worker and return scanned text through Tesseract OCR.

:sparkles: (ocr): Integrated Tesseract worker

---

frontend/apps/slip-snapper/src/app/components/TakePictureButton.tsx

Created component using text produced by Tesseract

:sparkles: (ocr): Used Tesseract Text

---

backend/api/apps/server.js
backend/api/apps/src/index.js
backend/api/apps/tests/index.test.js
backend/api/package.json

Added the skeleton of login call
Added unit test for login call
Slight change to add user call
Slight change to unit test for add user

🎨 (feature/api) Added the skeleton of login call

---

frontend/apps/slip-snapper/src/app/pages/Profile.tsx

Added new UI to the profile page

💄  (ui): Added ui to the profile page

---

backend/api/apps/src/index.js
backend/api/apps/tests/index.test.js
frontend/apps/slip-snapper/src/app/components/FetchData.js
frontend/apps/slip-snapper/src/app/pages/Home.tsx

Updated generate report
Added unit test for generate report
Updated frontend to reflect change to port number
Updated frontend generate report call

🎨 (feature-api): Updated the generate report api call

---

frontend/apps/slip-snapper/src/app/pages/Login.tsx
frontend/apps/slip-snapper/src/app/pages/Register.tsx

Added frontend call for login
Added frontend call for register

🎨 (Feature/api): Added frontend functions for authentication functionality

---

frontend/apps/slip-snapper/src/app/pages/Profile.tsx

Updated and Added UI in the profile page

💄 (ui): Updated UI on the profile page

---

backend/database/prisma/docker-compose.yml

Setup Docker to startup the database

✨ (db) setup Docker 

---

backend/database/prisma/prisma/migrations/20220529191053_init/migration.sql

:package: : (db) schema update

---

backend/database/prisma/prisma/schema.prisma

connect to the database and create the db schemas namely Users, Slips and Items

✨  (db) create db schemas

---

frontend/apps/slip-snapper/src/app/pages/Profile.tsx
frontend/apps/slip-snapper/src/app/theme/profile.css

Added a css file to enhance the styling of the profile page. Added a logout feature to the profile page.

💄(ui): Added css file and logout for Profile page

---

frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
frontend/apps/slip-snapper/src/app/theme/viewReports.css

Added components to the ViewReports page, added a css file to enhance the UI.

💄(ui): Added Ui to the ViewReports page

---

README.md
frontend/apps/slip-snapper/src/app/pages/Register.tsx

Updated UI of Register Page to be in line with Login Page

:lipstick: (ui): Updated Register Page UI

---

frontend/apps/slip-snapper/src/app/pages/Login.tsx
frontend/apps/slip-snapper/src/app/pages/Register.tsx
frontend/apps/slip-snapper/src/app/theme/LoginRegister.css

Added dynamic background and logo

:lipstick: (ui): Updated Login Page UI

---

backend/api/apps/src/db.js
backend/api/apps/src/index.js
backend/api/apps/src/routes/report.js
backend/api/apps/tests/db.test.js
backend/api/apps/tests/index.test.js
backend/api/package.json
backend/api/yarn.lock

Added budget api calls and unit tests skeletons
Added db base files for future use

✨ (Feature/api): Added budget api calls and db connection basics

---

frontend/apps/slip-snapper/src/app/pages/Register.tsx

Updated the User Interface to be more interactive and user friendly.

💄(ui): Updated the Register Page's UI

---

frontend/apps/slip-snapper/src/app/pages/Login.tsx
frontend/apps/slip-snapper/src/app/pages/Register.tsx
frontend/apps/slip-snapper/src/app/theme/login.css
frontend/apps/slip-snapper/src/app/theme/register.css

Updated this styling in the register page, formatted the css files.

💄(ui): Updated the CSS in register page

---

frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
frontend/apps/slip-snapper/src/app/theme/login.css
frontend/apps/slip-snapper/src/app/theme/register.css

Wrote tests to make sure login page renders correctly, fixed minor bug regarding buttons in mobile view

✅ (login): Wrote jest tests for login page

---

frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
frontend/apps/slip-snapper/src/app/pages/Login.tsx
frontend/apps/slip-snapper/src/app/pages/Register.tsx

Added Jest tests for rendering and user input.

✅ (tests) : Added Jest testing for Login & Register pages

---

frontend/apps/slip-snapper/src/app/pages/Profile.tsx
frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx

Added a popup for users to specify budget changes. Added prompt for users to confirm logout.

💄 (ui): Added popups for the Logout and budget

---

frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx

Added UI for dynamic lists of items in the edit slips page

💄(ui): Added UI for the Edit Slips page

---

frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx

Changed input area to a grid layout on Edit Slip page.

:lipstick: (ui): Edited Edit Slip page UI

---

backend/api/apps/textProcessor/text_parser/parser.js

Created basic total extraction function

:sparkles: (feature/textparser): Basic total extraction

---

frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
frontend/apps/slip-snapper/src/app/pages/Profile.tsx

After a user updates their weekly/monthly budget, the UI will update to these changes.

:lipstick: (ui) Budget updates after user input

---

backend/api/apps/textProcessor/text_parser/parser.js

Changed date and total extractor to work with array of text.

:ok_hand: (feature/textparser): total and date extraction with array

---

frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
frontend/apps/slip-snapper/src/app/components/TakePictureButton.tsx
frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
frontend/apps/slip-snapper/src/app/pages/Profile.tsx

Added Jest tests for the Edit slips page

✅ (tests) : Added rendering tests for the Edit Slips page

---

frontend/apps/slip-snapper/src/app/pages/Profile.tsx
frontend/apps/slip-snapper/src/app/theme/profile.css

Added a progress bar for a user to keep track of their budget.

:lipstick: (ui) Added a progress bar for budgets

---

backend/api/apps/textProcessor/text_parser/parser.js

Created basic item extraction function

:sparkles: (feature/textparser): Basic item extraction

---

backend/api/apps/textProcessor/text_parser/parser.js

Grouped slip parsed content into single array object

:ok_hand: (feature/textparser): Grouped slip content

---

frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx

Displays values scanned from the slips and allows users to edit them

💄 (ui) : Updated editslip UI

---

frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
frontend/apps/slip-snapper/src/app/pages/Profile.tsx

Added Jest tests to check if user statistics are rendered correctly

✅ (test): added Jest tests for the Profile Page

---

frontend/apps/slip-snapper/src/app/components/EditBudgets.tsx
frontend/apps/slip-snapper/src/app/pages/Profile.tsx

Added modal component with checkboxes to manage which categories have budgets.

:lipstick: (ui): Added component for budget editing

---

frontend/apps/slip-snapper/src/app/components/ReportItem.tsx
frontend/apps/slip-snapper/src/app/pages/Home.tsx

Added components for Home Page, also updated some UI

💄(ui): Added components for Home page

---

frontend/apps/slip-snapper/src/app/Tests/Home.spec.tsx
frontend/apps/slip-snapper/src/app/Tests/__snapshots__/App.spec.tsx.snap
frontend/apps/slip-snapper/src/app/components/ReportItem.tsx
frontend/apps/slip-snapper/src/app/components/ReportTotal.tsx
frontend/apps/slip-snapper/src/app/pages/Home.tsx

Added a component for the report card, also fixed a minor bug in the Home page

💄 (ui) : Added Component for Report Totals

---

frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
frontend/apps/slip-snapper/src/app/Tests/Home.spec.tsx
frontend/apps/slip-snapper/src/app/components/ReportTotal.tsx
frontend/apps/slip-snapper/src/app/pages/Home.tsx

Fixed Unit Testing for the Report Totals

✅ (tests): Fixed Tests for the ReportTotals

---

frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
frontend/apps/slip-snapper/src/app/components/ViewReportItem.tsx
frontend/apps/slip-snapper/src/app/components/ViewReportItems.tsx
frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
frontend/apps/slip-snapper/src/app/theme/viewReports.css

Updated the CSS for the reports page.  Added unit testing.

💄 (ui): Updated CSS for Reports page

---

frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
frontend/apps/slip-snapper/src/app/components/Budget.tsx
frontend/apps/slip-snapper/src/app/components/EditBudgets.tsx
frontend/apps/slip-snapper/src/app/components/UserStats.tsx
frontend/apps/slip-snapper/src/app/pages/Profile.tsx

Updated UI for the Budgets Component. Created a component for the User Statistics. Removed unnecessary testing.

💄 (ui): Added Component for User Stats

---

backend/api/apps/src/db.js
backend/api/apps/src/index.js
backend/api/apps/src/routes/report.js
backend/api/apps/tests/routes/auth.test.js
backend/api/apps/tests/routes/items.test.js
backend/api/apps/tests/routes/report.test.js

Added get report api skeleton
Updated generate report api call
Added unit test for get statistics call

(Feature/api): Added get report api skeleton

---

frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
frontend/apps/slip-snapper/src/app/theme/addEntry.css

Updated UI and functionality for the add slip page.

💄 (ui): Updated UI for the add entry page

---

backend/api/apps/textProcessor/text_parser/parser.js

additionally basic text correction

🚧 (parser): Expansion of text parser

---

frontend/apps/slip-snapper/src/AWS/S3Bucket.ts
frontend/apps/slip-snapper/src/app/components/ReportItem.tsx
frontend/apps/slip-snapper/src/app/pages/Register.tsx

Added function to get objects from S3

✨ (S3): added function to get objects from S3

---

frontend/apps/slip-snapper/src/AWS/S3Bucket.js
frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx

Work In Progress: Render Total for the Add Entry Page

🚧 (ui): Render Total for the Add Entry Page

---

frontend/apps/slip-snapper/src/app/components/ReportItem.tsx
frontend/apps/slip-snapper/src/app/theme/reportItem.css

Made provisions for different screen sizes so that cards in Recent Reports section scale accordingly

💄 (ui): Updated Recent Reports layout on Home Page

---

README.md
backend/api/apps/src/routes/S3Bucket.js
backend/api/apps/src/routes/report.js
backend/api/apps/tests/routes/report.test.js
backend/api/package.json
backend/api/yarn.lock
frontend/apps/slip-snapper/src/api/apiCall.js

Added the api call for get user reports
Added api call for getting specific reports
Updated the readme

(Feature/api) Updates to the api

---

frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx

Added functionality to view reports

💄 (ui): Added functionality to view reports

---

backend/api/apps/src/routes/S3Bucket.js
backend/api/apps/src/routes/report.js
frontend/apps/slip-snapper/src/api/apiCall.js

Added add api call to upload the file
Added delete api call to delete the file

(Feature/api) Added api calls

---

frontend/apps/slip-snapper/src/app/components/ReportTotal.tsx
frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx

Updated frontend to integrate with the API calls

💄 (ui): updated buttons to call API

---

frontend/apps/slip-snapper/src/app/components/FetchData.js
frontend/apps/slip-snapper/src/app/pages/FetchData.css

-Changed UI of EdiItem page which will need to be refactored to be EditReceipts. 
-Functionality of buttons and API functions have been suspended.

🚧 (refactor): Updated EditItem page UI

---

frontend/apps/slip-snapper/src/api/apiCall.js
frontend/apps/slip-snapper/src/app/components/FetchData.js
frontend/apps/slip-snapper/src/app/components/TakePictureButton.tsx
frontend/apps/slip-snapper/src/app/components/usePhotoGallery.js
frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
frontend/apps/slip-snapper/src/app/pages/Receipts.tsx

-Updated headers in API calls due to switch to Axios
-Updated incorrect labels and naming of components

🐛 (api): Updated headers in API calls

---

backend/api/apps/src/routes/S3Bucket.js
backend/api/apps/src/routes/auth.js
frontend/apps/slip-snapper/src/api/apiCall.js
frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
frontend/apps/slip-snapper/src/app/pages/Home.tsx
frontend/apps/slip-snapper/src/app/pages/Register.tsx
frontend/apps/slip-snapper/src/app/theme/home.css

Allows sign up functionality in the database and AWS bucket

✨ (feature): Implemented sign up functionality

---

frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
frontend/apps/slip-snapper/src/app/components/Budget.tsx
frontend/apps/slip-snapper/src/app/components/EditBudgets.tsx
frontend/apps/slip-snapper/src/app/components/UserStats.tsx
frontend/apps/slip-snapper/src/app/pages/Profile.tsx
frontend/apps/slip-snapper/src/app/theme/profile.css
frontend/apps/slip-snapper/src/app/theme/toasts.css

-Updated Profile Page UI as a whole
-Refactored the code responsible for dynamically populating components on Profile Page

💄 (ui): Updated Profile Page UI

---

backend/api/apps/src/db.js
backend/api/apps/src/routes/S3Bucket.js
backend/api/apps/src/routes/auth.js
backend/api/apps/src/routes/report.js
backend/api/apps/tests/routes/report.test.js
frontend/apps/slip-snapper/src/api/apiCall.js
frontend/apps/slip-snapper/src/app/components/ReportItem.tsx
frontend/apps/slip-snapper/src/app/components/ReportTotal.tsx
frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx

Added unit tests for certain api calls
Slight adjustment to frontend api callls
Added functionality to upload pdf after creating it
Slight change from generate to pdf and a get to a post for creating the pdf files

(Feature/api)

---

frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx

Tests const variables in isExceeded function

✅ (test): Added tests to Profile Page

---

backend/api/apps/src/routes/report.js
frontend/.gitignore
frontend/apps/slip-snapper/src/app/components/FetchData.js
frontend/apps/slip-snapper/src/app/components/ReportItem.tsx
frontend/apps/slip-snapper/src/app/components/ReportTotal.tsx
frontend/apps/slip-snapper/src/app/components/UserStats.tsx
frontend/apps/slip-snapper/src/app/components/usePhotoGallery.js
frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
frontend/apps/slip-snapper/src/app/pages/EditReceipt.tsx
frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
frontend/apps/slip-snapper/src/app/pages/Home.tsx
frontend/apps/slip-snapper/src/app/pages/Login.tsx
frontend/apps/slip-snapper/src/app/pages/Profile.tsx
frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx

Fixed minor bug
Made user data be stored in local storage

🎨 (feature/api) Frontend will now use the local storage of user

---

backend/api/apps/src/routes/item.js
backend/api/apps/tests/routes/items.test.js

Added unit test for the querys as well

🎨 (feature/api) Added api call to update slip and items

---

frontend/apps/slip-snapper/src/app/pages/Profile.tsx

WORK IN PROGRESS - Fixing budget rendering

🚧 (ui): Fixing budget rendering issue

---

backend/api/apps/src/db.js
backend/api/apps/src/routes/report.js
frontend/apps/slip-snapper/src/app/components/Budget.tsx
frontend/apps/slip-snapper/src/app/components/EditBudgets.tsx
frontend/apps/slip-snapper/src/app/theme/profile.css

Category Budgets now get and store states in the DB.

💄 (ui): Implemented Budget States

---

frontend/apps/slip-snapper/src/app/pages/Login.tsx
frontend/apps/slip-snapper/src/app/theme/login-register.css

-Replaced Register button with register prompt link.
-Added 'Forgot Password' link (no functionality)

💄 (ui): Updated Login UI

---

frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
frontend/apps/slip-snapper/src/app/pages/EditReceipt.tsx
frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx

-Added date picker to AddEntry, EditSlip, EditReceipt pages
-Updated date format to (YYYY/MM/DD)

♻️ (ui): Added date picker and updated date format

---

frontend/apps/slip-snapper/src/app/components/ProfileImage.tsx
frontend/apps/slip-snapper/src/app/pages/Profile.tsx
frontend/apps/slip-snapper/src/app/theme/profile.css

-Updated layout of profile image in User Details section
-Moved Personal Budget to User Details section
-(Work in Progress) Added profile image selector feature

🚧 (ui): Updated User Details section

---

backend/api/apps/src/db.js

please pass through a date string when creating a slip. the individually incremental numbers for slips and reports are implemented and tested with the frontend as well.

🚧 (db queries) queries adjusted for string dates

---

.github/workflows/FrontendCItest.yml
.github/workflows/index.yml
frontend/apps/slip-snapper/src/api/apiCall.js
frontend/apps/slip-snapper/src/app/App.tsx
frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
frontend/apps/slip-snapper/src/app/pages/ForgotPass.tsx
frontend/apps/slip-snapper/src/app/pages/Login.tsx
frontend/apps/slip-snapper/src/app/pages/Profile.tsx
frontend/apps/slip-snapper/src/app/pages/Register.tsx
frontend/apps/slip-snapper/src/app/theme/login-register.css

-Added ForgotPassword page
-Refactored Login and Register pages.
-Register page now only requires username, email and password (first and last names removed)
-Updated signupA function to account for this change
-DB will need to be updated to account for this change
-Updated unit testing

✨(ui): Added ForgotPassword page

---

frontend/apps/slip-snapper/src/app/components/TakePictureButton.tsx
frontend/apps/slip-snapper/src/app/components/UserStats.tsx
frontend/apps/slip-snapper/src/app/pages/Home.tsx
frontend/apps/slip-snapper/src/app/pages/Profile.tsx
frontend/apps/slip-snapper/src/app/theme/fab-home.css
frontend/apps/slip-snapper/src/app/theme/home.css
frontend/apps/slip-snapper/src/app/theme/profile.css
frontend/apps/slip-snapper/src/app/theme/user-stats.css

- Updated TakePictureButton UI on Home page to be more dynamic
- Added descriptions to sections on Profile page for improved UX

💄 (ui): Various UI updates

---

backend/api/apps/src/db.js

- dates adjusted to be relative to the current week and month
- getusergeneralbudgets returns a percentages, weeklyTotal and monthlyTotal objects

🐛 dates adjusted to be relative to the current week and month

---

frontend/apps/slip-snapper/src/app/components/SlipItems.tsx
frontend/apps/slip-snapper/src/app/pages/Profile.tsx
frontend/apps/slip-snapper/src/app/theme/slip-items.css

- Refactored UI of Receipts page
- Fixed some bugs with toggle states

🚧 (ui): Receipts Page refactor

---

backend/api/apps/src/db.js
backend/api/apps/src/routes/report.js

- get reports items function returns items relative to the dates
- reports file updated to paaa through date strings

🐛 (feature/reports) updated reports to return items within a given time frame

---

frontend/apps/slip-snapper/src/app/components/SlipItems.tsx
frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
frontend/apps/slip-snapper/src/app/theme/viewReports.css

💄 (ui): Updated UI of Reports Page

---

backend/api/apps/src/db.js

- expected return object; two arrays 
- namely averagesArray of 4 values, the values are listed in descending order in the sense that the value at index 0 is the last point in the graph and the value at index 3 is the first point.
- also expect a futureDates array of 4 dates. the dates are listed in descending order in the sense that the value at index 0 is the last date in the graph and the value at index 3 is the first date.

✨ (db query) expenditure forecasting imlemented

---

backend/api/apps/src/routes/auth.js
backend/api/apps/src/routes/item.js
backend/api/apps/src/routes/ocr.js
backend/api/apps/src/routes/report.js
backend/api/apps/src/routes/stats.js
backend/api/apps/tests/parser.test.js
backend/api/apps/tests/routes/auth.test.js
backend/api/apps/textProcessor/text_parser/parser.js
frontend/apps/slip-snapper-e2e/src/integration/home-integration.spec.ts
frontend/apps/slip-snapper-e2e/src/integration/login-integration.spec.ts
frontend/apps/slip-snapper-e2e/src/integration/navigation-integration.spec.ts
frontend/apps/slip-snapper/src/app/components/Budget.tsx
frontend/apps/slip-snapper/src/app/components/EditBudgets.tsx
frontend/apps/slip-snapper/src/app/components/UserStats.tsx
frontend/apps/slip-snapper/src/app/pages/EditReceipt.tsx
frontend/apps/slip-snapper/src/app/pages/Home.tsx
frontend/apps/slip-snapper/src/app/pages/Login.tsx
frontend/apps/slip-snapper/src/app/pages/Profile.tsx
frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
frontend/apps/slip-snapper/src/app/tests/api/Session.test.js
frontend/apps/slip-snapper/src/app/tests/api/apiCall.test.js
frontend/apps/slip-snapper/src/app/tests/pages/EditReceipt.test.tsx
frontend/package.json
frontend/yarn.lock

-apiCall tets
-parser test
-editReceipt test
-destroySession test
-revert status codes
-crash fixes and error catches for some responses

✅ (tests): additional tests + fixes

---

backend/api/apps/src/routes/auth.js
backend/api/apps/tests/routes/auth.test.js
backend/api/prisma/migrations/20220922205543_final/migration.sql
backend/api/prisma/schema.prisma

- Password
-  check that the password is minimum eight characters, 
-  at least one uppercase letter, one lowercase letter,
-  one number and one special character
- Email
- email validation
- General
- general input validation

✨ (feature/validation) validation for auth.js complete

---

backend/api/apps/src/routes/item.js
backend/api/apps/tests/routes/items.test.js

- There are only two fields that are user defined
- limit the user input to just letters, numbers and a space

✨ (feature/validation) Item validation

---

frontend/apps/slip-snapper-e2e/src/integration/home-integration.spec.ts
frontend/apps/slip-snapper-e2e/src/integration/login-integration.spec.ts
frontend/apps/slip-snapper-e2e/src/integration/navigation-integration.spec.ts
frontend/apps/slip-snapper/src/app/components/Budget.tsx
frontend/apps/slip-snapper/src/app/components/EditBudgets.tsx
frontend/apps/slip-snapper/src/app/components/NavButtons.tsx
frontend/apps/slip-snapper/src/app/pages/ForgotPass.tsx
frontend/apps/slip-snapper/src/app/pages/Login.tsx
frontend/apps/slip-snapper/src/app/pages/Profile.tsx
frontend/apps/slip-snapper/src/app/pages/Register.tsx
frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx

-Register fix
-Integration test update
-code cleanup

🐛 (register): fix for register token
